// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrNzsuAXOkTdAQcCkfbnuLiHYaCniwKg',
    appId: '1:694766596118:web:4f50864473f1d0ecb30537',
    messagingSenderId: '694766596118',
    projectId: 'school-management-9b692',
    authDomain: 'school-management-9b692.firebaseapp.com',
    storageBucket: 'school-management-9b692.firebasestorage.app',
    measurementId: 'G-JH2BC9L98G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfrBA_Y5oDYfoN4ejib9a3dvWB-bQ5N34',
    appId: '1:694766596118:android:b39ed9ba27f693c4b30537',
    messagingSenderId: '694766596118',
    projectId: 'school-management-9b692',
    storageBucket: 'school-management-9b692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1g7xtG8WXmPEYRL12YU06tEvpdW4IbwY',
    appId: '1:694766596118:ios:ae9be1c712fde057b30537',
    messagingSenderId: '694766596118',
    projectId: 'school-management-9b692',
    storageBucket: 'school-management-9b692.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1g7xtG8WXmPEYRL12YU06tEvpdW4IbwY',
    appId: '1:694766596118:ios:ae9be1c712fde057b30537',
    messagingSenderId: '694766596118',
    projectId: 'school-management-9b692',
    storageBucket: 'school-management-9b692.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

}